name: CI

on: push

jobs:

  Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Fetch your code
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..
    - name: Build
      run: cmake --build build
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
